### ISSUE TITLE
Problem Plotting with CVODE_BDF due to Solution Type

### ISSUE THREAD

**Issue by donaldlee3** [SciML/Sundials.jl#298]
Odd plotting behavior and solution handling with `CVODE_BDF`, due to solution type of function being `Array{Float64,0}`.

```
using DifferentialEquations
using Sundials
using Plots

function lorenz!(du,u,p,t)
 du[1] = 10.0*(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz!,u0,tspan)

# solving w/o and w/ CVODE_BDF
sol1 = solve(prob)
sol2 = solve(prob, CVODE_BDF())

## Plotting

# works for both solutions 
plot(sol1, vars=(0,1))
plot(sol2, vars=(0,1))

# off for sol2
testfxn1(t) = sol1(t, idxs=1)
plot(0:0.1:100, testfxn1)

testfxn2(t) = sol2(t, idxs=1)
plot(0:0.1:100, testfxn2)

## Solution Type

type1 = typeof(testfxn1(1))     # Float64
type2 = typeof(testfxn2(1))     # Array{Float64,0}
```

# Plot for testfxn1
![image](https://user-images.githubusercontent.com/57191391/106033682-029fe800-60a0-11eb-903f-ed5acb17ba41.png)

# Plot for testfxn2
![image](https://user-images.githubusercontent.com/57191391/106033773-177c7b80-60a0-11eb-8b3b-f0af100c1136.png)

**Comment by FelixNoessler** [comment]
I have experienced very similar behaviour. In the tutorial on solution handling of the DifferentialEquations.jl package ([link](https://diffeq.sciml.ai/stable/basics/solution/#Interpolations-and-Calculating-Derivatives)) it is shown that the idxs can be either a number or an Array. 

This is works for example with the `Tsit()` solver. However, if I use solvers from the Sundials package then I will get error messages.

This code fails because idxs is given here as a Float and not a as an array.
```
using Sundials
function lorenz!(du,u,p,t)
 du[1] = 10.0(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz!,u0,tspan)

sol = solve(prob,CVODE_Adams())

println(sol(90:1:100, idxs=1))
```
This is the error message:
`ERROR: LoadError: MethodError: Cannot `convert` an object of type Array{Float64, 0} to an object of type Float64`

The same code is working with  `sol(90:1:100, idxs=[1])`

So maybe there is just a conversion to a Array of the idxs parameter missing?

**Comment by FelixNoessler** [comment]
I am beginner in Julia, maybe in the file [integrator_types.jl](https://github.com/SciML/Sundials.jl/blob/master/src/common_interface/integrator_types.jl) is the problem?

I tried to replace `out[idxs]` with `out[idxs, :]` in the  `function (integrator::CVODEIntegrator)` but this changed nothing..

```
function (integrator::CVODEIntegrator)(
    t::Number,
    deriv::Type{Val{T}} = Val{0};
    idxs = nothing,
) where {T}
    out = similar(integrator.u)
    integrator.flag = @checkflag CVodeGetDky(integrator.mem, t, Cint(T), out)
    return idxs == nothing ? out : out[idxs]
end

function (integrator::CVODEIntegrator)(
    out,
    t::Number,
    deriv::Type{Val{T}} = Val{0};
    idxs = nothing,
) where {T}
    integrator.flag = @checkflag CVodeGetDky(integrator.mem, t, Cint(T), out)
    return idxs == nothing ? out : @view out[idxs]
end
```

**Comment by ChrisRackauckas** [comment]
Should be fixed by https://github.com/SciML/SciMLBase.jl/pull/127
