### ISSUE TITLE
precompile issue

### ISSUE THREAD

**Issue by alok** [SciML/Sundials.jl#303]
Running julia nightly on MACOS 10.15, but that's using a download of the official nightly binaries. `]add DifferentialEquations` gave this issue when it got to precompiling Sundials:

```
ERROR: LoadError: InitError: could not load library "/Users/alokbeniwal/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib"
dlopen(/Users/alokbeniwal/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib, 1): Library not loaded: @rpath/libsuitesparseconfig.5.4.0.dylib
  Referenced from: /Users/alokbeniwal/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib
  Reason: image not found
```

**Comment by ChrisRackauckas** [comment]
Try doing `]build Sundials` again. Looks like it may have not downloaded. Why such an old version? Are you on Julia v.1.6?

**Comment by alok** [comment]
I'm using the 1.7 nightly

**Comment by ChrisRackauckas** [comment]
If you're using the nightly it's on you to debug it. That could be a BB issue or something.

**Comment by alok** [comment]
BB?

**Comment by ChrisRackauckas** [comment]
BinaryBuilder. I am not sure whether BinaryProvider.jl is updated for v1.7. But again, v1.7 is only for people developing the packages so I assume that if you're using it you're likely debugging these packages. Otherwise, use the stable release.

**Comment by integzz** [comment]
Hi, @ChrisRackauckas. I ran Julia v1.6.1 on MACOS 10.15 and tried to precompile DifferentialEquations, but failed due to LoadError of Sundials. The message is

```
LoadError: InitError: could not load library "/Users/integrator/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib"
dlopen(/Users/integrator/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib, 1): Library not loaded: @rpath/libsuitesparseconfig.5.4.0.dylib
  Referenced from: /Users/integrator/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib
  Reason: image not found
....
```

![image](https://user-images.githubusercontent.com/46377665/123204663-25b5b300-d4eb-11eb-9d3b-a0ab97c19e97.png)


![image](https://user-images.githubusercontent.com/46377665/123204606-06b72100-d4eb-11eb-97e5-494c1d9951ea.png)

I am sure how to solve this. Can I precompile Sundials using a local file? 

> BTW, DifferentialEquations.jl is quite important to me.

**Comment by ChrisRackauckas** [comment]
What CPU? `versioninfo()`?

**Comment by integzz** [comment]
> What CPU? `versioninfo()`?

![image](https://user-images.githubusercontent.com/46377665/123290505-ec5d6180-d543-11eb-90d0-9a405c8d76b3.png)

**Comment by staticfloat** [comment]
@integzz can you create a new project and add `Sundials_jll` to it, to see if the latest version works for you?

Your error mentions an inability to load `libsuitesparseconfig.5.4.0.dylib`.  This should be provided by the default Julia installation.  Can you show me the output of:

```
julia> using Libdl
       filter(Libdl.dllist()) do f
       occursin("suite", f)
       end
2-element Vector{String}:
 "/Users/julia/dist/x86_64/julia-1.6.1/lib/julia/./libsuitesparseconfig.5.4.0.dylib"
 "/Users/julia/dist/x86_64/julia-1.6.1/lib/julia/libsuitesparse_wrapper.dylib"
```

**Comment by integzz** [comment]
> Sundials_jll

It seems no...

![image](https://user-images.githubusercontent.com/46377665/123354236-cfea1500-d595-11eb-9e4b-df1a903c1e30.png)

However, there is `libsuitesparseconfig` whose version is 5.10. How can I solve this problem?

![image](https://user-images.githubusercontent.com/46377665/123354381-16d80a80-d596-11eb-82fe-00063bf0bb8d.png)

**Comment by giordano** [comment]
@integzz could you please paste the output here, quoting it in triple backquotes
````
```
like this
```
````
?  Screenshots are not very useful.

That said, the problem is that you're loading a libsuitesparseconfig from somewhere else.  Do you have the environment variable `DYLD_FALLBACK_LIBRARY_PATH` set to some special values?  You can see that inside julia with
```julia
ENV["DYLD_FALLBACK_LIBRARY_PATH"]
```

**Comment by integzz** [comment]
> @integzz could you please paste the output here, quoting it in triple backquotes
> 
> ````
> 
> ```
> 
> like this
> 
> ```
> 
> ````
> 
> ?  Screenshots are not very useful.
> 
> 
> 
> That said, the problem is that you're loading a libsuitesparseconfig from somewhere else.  Do you have the environment variable `DYLD_FALLBACK_LIBRARY_PATH` set to some special values?  You can see that inside julia with
> 
> ```julia
> 
> ENV["DYLD_FALLBACK_LIBRARY_PATH"]
> 
> ```

I am truly sorry. I have reinstalled Julia from Homebrew Cask instead of the previous binary version (from Homebrew core, compiled by cmake, llvm and gcc). Currently, the error has disappeared. And I don't want to reproduce it.

The error was raised, because the SuiteSparse has a higher version. I think the brew manifest needs to be added some constraints to guarantee a right version of every dependency.

**Comment by staticfloat** [comment]
> The error was raised, because the SuiteSparse has a higher version. I think the brew manifest needs to be added some constraints to guarantee a right version of every dependency.

Yep, that looks like the issue!  For the record, we highly recommend using the official https://julialang.org binaries, they will have all the dependency versions set to work properly.  :)

**Comment by ChrisRackauckas** [comment]
Fantastic.
